const languageStorageKey = "agintiflow.website.language";

const translations = {
  en: {
    documentTitle: "AgInTiFlow | Low-cost project-aware agents",
    metaDescription:
      "AgInTiFlow is a Web and CLI agent workspace with DeepSeek/Venice/OpenAI routing, visible tool calls, durable sessions, scouts, SCS supervision, AAPS workflows, and guarded local execution.",
    brandHomeAria: "AgInTiFlow home",
    primaryNavAria: "Primary navigation",
    navScreenshots: "Screenshots",
    navPlatform: "Platform",
    navDocs: "Docs",
    navSafety: "Safety",
    navLaunch: "Launch Web UI",
    languageLabel: "Language",
    heroEyebrow: "Web + CLI agent workspace",
    heroTitle: "AgInTi Flow -- low-cost, project-aware agents",
    heroSubtitle:
      "Use the same agent workspace from Web or CLI, with DeepSeek/Venice/OpenAI routing, visible tool calls, durable sessions, scouts, SCS supervision, AAPS workflows, and guarded local execution.",
    installAria: "Install AgInTiFlow",
    copyButton: "Copy",
    copiedPrefix: "Copied: {text}",
    copyFailed: "Copy failed. Select the command and copy it manually.",
    heroScreenshots: "View real app screenshots",
    capabilitySummaryAria: "AgInTiFlow capability summary",
    heroPreviewAlt: "AgInTiFlow terminal launch screen with colorful banner, Docker workspace status, and interactive chat input.",
    heroPreviewTitle: "CLI + Web, one session",
    heroPreviewPrefix: "Start with",
    heroPreviewSuffix: "then inspect the same project sessions in the browser.",
    heroWebPreviewAlt: "AgInTiFlow web console showing conversation history and structured run output.",
    heroWebPreviewTitle: "Web console visibility",
    heroWebPreviewText: "The browser shows the conversation and run output from the same local workspace.",
    cardDefaultLabel: "Default route",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "Fast planning for browser, shell, and short coding tasks.",
    cardEscalationLabel: "Escalation",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "Complex implementation, debugging, and design decisions.",
    cardSafetyLabel: "Safe execution",
    cardSafetyTitle: "Docker + policy",
    cardSafetyText: "Read-only by default, explicit approval for setup commands.",
    screensEyebrow: "Real screenshots from the local app",
    screensTitle: "Daily agent work should feel inspectable, not mysterious.",
    screensText: "The carousel uses screenshots captured from the live AgInTiFlow app running at http://127.0.0.1:3210/.",
    screensCarouselAria: "AgInTiFlow screenshots",
    previousScreenshotAria: "Previous screenshot",
    nextScreenshotAria: "Next screenshot",
    screenshotSelectorAria: "Screenshot selector",
    showScreenshotAria: "Show screenshot {number}",
    slideOverviewAlt: "AgInTiFlow web app showing task controls, run output, and conversation history.",
    slideOverviewTitle: "Agent cockpit",
    slideOverviewText: "Route controls, mock run output, wrapper status, sandbox controls, and chat history in one page.",
    slideControlsAlt: "Task and model route controls in the AgInTiFlow web app.",
    slideControlsTitle: "Route and task controls",
    slideControlsText: "Pick smart routing, manual provider/model, shell access, command cwd, and package-install policy.",
    slideLogsAlt: "AgInTiFlow run output with structured session logs.",
    slideLogsTitle: "Structured run logs",
    slideLogsText: "See every model response, tool call, command result, and final answer as the session runs.",
    slideHistoryAlt: "AgInTiFlow conversation history panel after a mock run.",
    slideHistoryTitle: "Resume the conversation",
    slideHistoryText: "Sessions persist chat history so follow-up requests continue from the selected run.",
    slideMobileAlt: "AgInTiFlow responsive mobile layout.",
    slideMobileTitle: "Responsive by default",
    slideMobileText: "The same controls remain usable on narrow screens for quick monitoring and setup.",
    platformEyebrow: "Low-cost project automation",
    platformTitle: "One workspace, routed models, visible tools.",
    featureRoutingTitle: "Smart routing",
    featureRoutingText:
      "DeepSeek v4 flash handles fast work. DeepSeek v4 pro handles complex tasks. Manual OpenAI-compatible routes stay available.",
    featureWrappersTitle: "Wrapper tools",
    featureWrappersText: "Codex, Claude, Gemini, Copilot, and Qwen wrappers are optional advisory tools, not hard dependencies.",
    featureFilesTitle: "Safe file tools",
    featureFilesText: "List, read, search, write, and patch workspace files with path guardrails, hashes, and compact diffs.",
    featureMockTitle: "Mock mode",
    featureMockText: "Local mock routing verifies UI, API, tool execution, and CI smoke paths without DeepSeek or OpenAI credentials.",
    docsEyebrow: "Runtime documentation",
    docsTitle: "Choose the right execution mode for the job.",
    docsText:
      "AgInTiFlow documents Docker sandboxing, host full-access mode, durable tmux sessions, package installs, and rolling-plan autonomy as first-class product behavior.",
    safetyEyebrow: "Safety model",
    safetyTitle: "Useful automation with explicit boundaries.",
    safetyText:
      "AgInTiFlow keeps local commands guarded by an allowlist, stores resumable run history, and exposes sandbox status through APIs that do not leak API keys or npm tokens.",
    safetyItem1: "Docker read-only mode for inspection and tests.",
    safetyItem2: "Docker workspace-write mode only for approved setup commands.",
    safetyItem3: "Workspace edits stay inside the selected command directory and block secret-like paths.",
    safetyItem4: "Package installs default to approval-required policy.",
    safetyItem5: "NPM publish, token commands, sudo, destructive git, and shell chaining are blocked.",
    bottomSummaryAria: "AgInTiFlow summary",
    bottomStatement:
      "AgInTiFlow keeps real project work cheap and inspectable: route with DeepSeek/Venice/OpenAI, watch every tool call, resume durable sessions, scout before complex edits, gate risky work with SCS, and use AAPS for larger workflows.",
    footerProduct: "AgInTiFlow by AgInTi Inc.",
  },
  ar: {
    documentTitle: "AgInTiFlow | وكلاء منخفضو التكلفة وواعون بالمشروع",
    metaDescription:
      "AgInTiFlow مساحة عمل وكيل عبر Web و CLI مع توجيه DeepSeek/Venice/OpenAI، واستدعاءات أدوات مرئية، وجلسات دائمة، وscouts، وإشراف SCS، وسير عمل AAPS، وتنفيذ محلي محمي.",
    brandHomeAria: "الصفحة الرئيسية لـ AgInTiFlow",
    primaryNavAria: "التنقل الرئيسي",
    navScreenshots: "لقطات الشاشة",
    navPlatform: "المنصة",
    navSafety: "الأمان",
    navLaunch: "تشغيل واجهة الويب",
    languageLabel: "اللغة",
    heroEyebrow: "مساحة عمل وكيل عبر Web + CLI",
    heroTitle: "AgInTi Flow -- وكلاء منخفضو التكلفة وواعون بالمشروع",
    heroSubtitle: "استخدم مساحة عمل الوكيل نفسها من Web أو CLI، مع توجيه DeepSeek/Venice/OpenAI، واستدعاءات أدوات مرئية، وجلسات دائمة، وscouts، وإشراف SCS، وسير عمل AAPS، وتنفيذ محلي محمي.",
    installAria: "تثبيت AgInTiFlow",
    copyButton: "نسخ",
    copiedPrefix: "تم النسخ: {text}",
    copyFailed: "فشل النسخ. حدّد الأمر وانسخه يدويًا.",
    heroScreenshots: "عرض لقطات حقيقية للتطبيق",
    capabilitySummaryAria: "ملخص قدرات AgInTiFlow",
    cardDefaultLabel: "المسار الافتراضي",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "تخطيط سريع للمتصفح والطرفية ومهام البرمجة القصيرة.",
    cardEscalationLabel: "التصعيد",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "تنفيذ معقد، وتصحيح أخطاء، وقرارات تصميم.",
    cardSafetyLabel: "تنفيذ آمن",
    cardSafetyTitle: "Docker + سياسة",
    cardSafetyText: "قراءة فقط افتراضيًا، وموافقة صريحة لأوامر الإعداد.",
    screensEyebrow: "لقطات حقيقية من التطبيق المحلي",
    screensTitle: "يجب أن يكون عمل الوكيل اليومي قابلًا للفحص، لا غامضًا.",
    screensText: "يعرض الشريط لقطات ملتقطة من تطبيق AgInTiFlow الحي على http://127.0.0.1:3210/.",
    screensCarouselAria: "لقطات AgInTiFlow",
    previousScreenshotAria: "لقطة الشاشة السابقة",
    nextScreenshotAria: "لقطة الشاشة التالية",
    screenshotSelectorAria: "محدد لقطات الشاشة",
    showScreenshotAria: "عرض لقطة الشاشة {number}",
    slideOverviewAlt: "تطبيق AgInTiFlow يعرض عناصر التحكم، ومخرجات التشغيل، وسجل المحادثة.",
    slideOverviewTitle: "قمرة قيادة الوكيل",
    slideOverviewText: "تحكم بالمسارات، ومخرجات المحاكاة، وحالة المغلفات، والعزل، وسجل الدردشة في صفحة واحدة.",
    slideControlsAlt: "عناصر التحكم في المهمة ومسار النموذج داخل تطبيق AgInTiFlow.",
    slideControlsTitle: "تحكم بالمسار والمهمة",
    slideControlsText: "اختر التوجيه الذكي، أو المزود/النموذج يدويًا، ووصول الطرفية، ومجلد العمل، وسياسة تثبيت الحزم.",
    slideLogsAlt: "مخرجات تشغيل AgInTiFlow مع سجلات جلسة منظمة.",
    slideLogsTitle: "سجلات تشغيل منظمة",
    slideLogsText: "شاهد كل رد للنموذج، واستدعاء أداة، ونتيجة أمر، والإجابة النهائية أثناء التشغيل.",
    slideHistoryAlt: "لوحة سجل محادثات AgInTiFlow بعد تشغيل محاكاة.",
    slideHistoryTitle: "استئناف المحادثة",
    slideHistoryText: "تحتفظ الجلسات بسجل الدردشة حتى تتابع الطلبات اللاحقة من التشغيل المحدد.",
    slideMobileAlt: "تخطيط AgInTiFlow المتجاوب على الهاتف.",
    slideMobileTitle: "متجاوب افتراضيًا",
    slideMobileText: "تبقى عناصر التحكم نفسها قابلة للاستخدام على الشاشات الضيقة للمراقبة والإعداد السريع.",
    platformEyebrow: "أتمتة مشاريع منخفضة التكلفة",
    platformTitle: "مساحة عمل واحدة، نماذج موجهة، وأدوات مرئية.",
    featureRoutingTitle: "توجيه ذكي",
    featureRoutingText: "يتولى DeepSeek v4 flash الأعمال السريعة. ويتولى DeepSeek v4 pro المهام المعقدة. وتبقى المسارات المتوافقة مع OpenAI متاحة يدويًا.",
    featureWrappersTitle: "أدوات مغلفة",
    featureWrappersText: "مغلفات Codex وClaude وGemini وCopilot وQwen أدوات استشارية اختيارية وليست اعتماديات صلبة.",
    featureFilesTitle: "أدوات ملفات آمنة",
    featureFilesText: "اسرد واقرأ وابحث واكتب ورقّع ملفات مساحة العمل مع حواجز مسار وهاشات وفروق مختصرة.",
    featureMockTitle: "وضع المحاكاة",
    featureMockText: "يتحقق التوجيه المحلي الوهمي من الواجهة وواجهة API وتشغيل الأدوات ومسارات CI دون مفاتيح DeepSeek أو OpenAI.",
    safetyEyebrow: "نموذج الأمان",
    safetyTitle: "أتمتة مفيدة بحدود صريحة.",
    safetyText: "يحافظ AgInTiFlow على الأوامر المحلية ضمن قائمة سماح، ويخزن سجل تشغيل قابلًا للاستئناف، ويعرض حالة العزل عبر APIs لا تسرّب مفاتيح API أو رموز npm.",
    safetyItem1: "وضع Docker للقراءة فقط للفحص والاختبارات.",
    safetyItem2: "وضع كتابة مساحة عمل Docker لأوامر الإعداد المعتمدة فقط.",
    safetyItem3: "تبقى تعديلات مساحة العمل داخل مجلد الأوامر المحدد وتحجب المسارات الشبيهة بالأسرار.",
    safetyItem4: "تثبيت الحزم يتطلب الموافقة افتراضيًا.",
    safetyItem5: "نشر NPM، وأوامر الرموز، وsudo، وgit المدمر، وتسلسل أوامر الطرفية محجوبة.",
    bottomSummaryAria: "ملخص AgInTiFlow",
    bottomStatement: "يوجه AgInTiFlow العمل العادي عبر DeepSeek v4 flash، ويصعّد المهام المعقدة إلى DeepSeek v4 pro، ويحرر ملفات مساحة العمل بأدوات محروسة، ويمكنه استدعاء مغلفات Codex وClaude وGemini وCopilot وQwen عندما تضيف قيمة.",
    footerProduct: "AgInTiFlow من AgInTi Inc.",
  },
  de: {
    documentTitle: "AgInTiFlow | Günstige projektbewusste Agenten",
    metaDescription:
      "AgInTiFlow ist ein Web- und CLI-Agenten-Workspace mit DeepSeek/Venice/OpenAI-Routing, sichtbaren Tool-Calls, dauerhaften Sessions, Scouts, SCS-Supervision, AAPS-Workflows und geschützter lokaler Ausführung.",
    brandHomeAria: "AgInTiFlow Startseite",
    primaryNavAria: "Hauptnavigation",
    navScreenshots: "Screenshots",
    navPlatform: "Plattform",
    navSafety: "Sicherheit",
    navLaunch: "Web-UI starten",
    languageLabel: "Sprache",
    heroEyebrow: "Web + CLI Agenten-Workspace",
    heroTitle: "AgInTi Flow -- günstige, projektbewusste Agenten",
    heroSubtitle: "Nutze denselben Agenten-Workspace aus Web oder CLI, mit DeepSeek/Venice/OpenAI-Routing, sichtbaren Tool-Calls, dauerhaften Sessions, Scouts, SCS-Supervision, AAPS-Workflows und geschützter lokaler Ausführung.",
    installAria: "AgInTiFlow installieren",
    copyButton: "Kopieren",
    copiedPrefix: "Kopiert: {text}",
    copyFailed: "Kopieren fehlgeschlagen. Markiere den Befehl und kopiere ihn manuell.",
    heroScreenshots: "Echte App-Screenshots ansehen",
    capabilitySummaryAria: "AgInTiFlow Funktionsübersicht",
    cardDefaultLabel: "Standardroute",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "Schnelle Planung für Browser, Shell und kurze Coding-Aufgaben.",
    cardEscalationLabel: "Eskalation",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "Komplexe Implementierung, Debugging und Designentscheidungen.",
    cardSafetyLabel: "Sichere Ausführung",
    cardSafetyTitle: "Docker + Richtlinie",
    cardSafetyText: "Standardmäßig nur lesend, explizite Freigabe für Setup-Befehle.",
    screensEyebrow: "Echte Screenshots aus der lokalen App",
    screensTitle: "Tägliche Agentenarbeit sollte prüfbar wirken, nicht geheimnisvoll.",
    screensText: "Das Karussell nutzt Screenshots der laufenden AgInTiFlow-App unter http://127.0.0.1:3210/.",
    screensCarouselAria: "AgInTiFlow Screenshots",
    previousScreenshotAria: "Vorheriger Screenshot",
    nextScreenshotAria: "Nächster Screenshot",
    screenshotSelectorAria: "Screenshot-Auswahl",
    showScreenshotAria: "Screenshot {number} anzeigen",
    slideOverviewAlt: "AgInTiFlow-Webapp mit Aufgabensteuerung, Run-Ausgabe und Gesprächsverlauf.",
    slideOverviewTitle: "Agenten-Cockpit",
    slideOverviewText: "Routensteuerung, Mock-Ausgabe, Wrapper-Status, Sandbox-Kontrollen und Chatverlauf auf einer Seite.",
    slideControlsAlt: "Aufgaben- und Modellroutensteuerung in der AgInTiFlow-Webapp.",
    slideControlsTitle: "Routen- und Aufgabensteuerung",
    slideControlsText: "Wähle Smart Routing, manuellen Provider/Modell, Shell-Zugriff, Arbeitsverzeichnis und Paketinstallationsrichtlinie.",
    slideLogsAlt: "AgInTiFlow Run-Ausgabe mit strukturierten Sitzungslogs.",
    slideLogsTitle: "Strukturierte Run-Logs",
    slideLogsText: "Sieh jede Modellantwort, jeden Tool-Aufruf, jedes Befehlsergebnis und die finale Antwort während der Ausführung.",
    slideHistoryAlt: "AgInTiFlow Gesprächsverlauf nach einem Mock-Run.",
    slideHistoryTitle: "Gespräch fortsetzen",
    slideHistoryText: "Sitzungen speichern den Chatverlauf, damit Folgeanfragen aus dem gewählten Run weiterlaufen.",
    slideMobileAlt: "Responsives mobiles AgInTiFlow-Layout.",
    slideMobileTitle: "Standardmäßig responsiv",
    slideMobileText: "Dieselben Kontrollen bleiben auf schmalen Bildschirmen für schnelles Monitoring und Setup nutzbar.",
    platformEyebrow: "Günstige Projektautomation",
    platformTitle: "Ein Workspace, geroutete Modelle, sichtbare Tools.",
    featureRoutingTitle: "Smart Routing",
    featureRoutingText: "DeepSeek v4 flash übernimmt schnelle Arbeit. DeepSeek v4 pro übernimmt komplexe Aufgaben. Manuelle OpenAI-kompatible Routen bleiben verfügbar.",
    featureWrappersTitle: "Wrapper-Tools",
    featureWrappersText: "Codex-, Claude-, Gemini-, Copilot- und Qwen-Wrapper sind optionale Beratungstools, keine harten Abhängigkeiten.",
    featureFilesTitle: "Sichere Dateitools",
    featureFilesText: "Workspace-Dateien auflisten, lesen, suchen, schreiben und patchen, mit Pfadschutz, Hashes und kompakten Diffs.",
    featureMockTitle: "Mock-Modus",
    featureMockText: "Lokales Mock-Routing prüft UI, API, Tool-Ausführung und CI-Smoke-Pfade ohne DeepSeek- oder OpenAI-Zugangsdaten.",
    safetyEyebrow: "Sicherheitsmodell",
    safetyTitle: "Nützliche Automatisierung mit klaren Grenzen.",
    safetyText: "AgInTiFlow schützt lokale Befehle über eine Allowlist, speichert fortsetzbare Run-Historie und zeigt Sandbox-Status über APIs, ohne API-Keys oder npm-Tokens offenzulegen.",
    safetyItem1: "Docker-Nur-Lesen-Modus für Inspektion und Tests.",
    safetyItem2: "Docker-Workspace-Schreibmodus nur für freigegebene Setup-Befehle.",
    safetyItem3: "Workspace-Edits bleiben im gewählten Befehlsverzeichnis und blockieren geheimnisähnliche Pfade.",
    safetyItem4: "Paketinstallationen erfordern standardmäßig Zustimmung.",
    safetyItem5: "NPM-Publishing, Token-Befehle, sudo, destruktives git und Shell-Verkettung sind blockiert.",
    bottomSummaryAria: "AgInTiFlow Zusammenfassung",
    bottomStatement: "AgInTiFlow routet normale Arbeit über DeepSeek v4 flash, eskaliert komplexe Aufgaben an DeepSeek v4 pro, bearbeitet Workspace-Dateien mit geschützten Tools und kann Codex-, Claude-, Gemini-, Copilot- und Qwen-Wrapper aufrufen, wenn sie Mehrwert bringen.",
    footerProduct: "AgInTiFlow von AgInTi Inc.",
  },
  es: {
    documentTitle: "AgInTiFlow | Agentes de bajo costo conscientes del proyecto",
    metaDescription:
      "AgInTiFlow es un workspace Web y CLI para agentes con routing DeepSeek/Venice/OpenAI, llamadas de herramientas visibles, sesiones durables, scouts, supervisión SCS, workflows AAPS y ejecución local protegida.",
    brandHomeAria: "Inicio de AgInTiFlow",
    primaryNavAria: "Navegación principal",
    navScreenshots: "Capturas",
    navPlatform: "Plataforma",
    navSafety: "Seguridad",
    navLaunch: "Abrir Web UI",
    languageLabel: "Idioma",
    heroEyebrow: "Workspace de agente Web + CLI",
    heroTitle: "AgInTi Flow -- agentes de bajo costo conscientes del proyecto",
    heroSubtitle: "Usa el mismo workspace de agente desde Web o CLI, con routing DeepSeek/Venice/OpenAI, llamadas de herramientas visibles, sesiones durables, scouts, supervisión SCS, workflows AAPS y ejecución local protegida.",
    installAria: "Instalar AgInTiFlow",
    copyButton: "Copiar",
    copiedPrefix: "Copiado: {text}",
    copyFailed: "No se pudo copiar. Selecciona el comando y cópialo manualmente.",
    heroScreenshots: "Ver capturas reales de la app",
    capabilitySummaryAria: "Resumen de capacidades de AgInTiFlow",
    cardDefaultLabel: "Ruta predeterminada",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "Planificación rápida para navegador, shell y tareas cortas de código.",
    cardEscalationLabel: "Escalado",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "Implementación compleja, depuración y decisiones de diseño.",
    cardSafetyLabel: "Ejecución segura",
    cardSafetyTitle: "Docker + política",
    cardSafetyText: "Solo lectura por defecto, aprobación explícita para comandos de configuración.",
    screensEyebrow: "Capturas reales desde la app local",
    screensTitle: "El trabajo diario con agentes debe ser inspeccionable, no misterioso.",
    screensText: "El carrusel usa capturas de la app AgInTiFlow en vivo en http://127.0.0.1:3210/.",
    screensCarouselAria: "Capturas de AgInTiFlow",
    previousScreenshotAria: "Captura anterior",
    nextScreenshotAria: "Captura siguiente",
    screenshotSelectorAria: "Selector de capturas",
    showScreenshotAria: "Mostrar captura {number}",
    slideOverviewAlt: "App web AgInTiFlow con controles de tarea, salida de ejecución e historial de conversación.",
    slideOverviewTitle: "Cabina del agente",
    slideOverviewText: "Controles de ruta, salida mock, estado de wrappers, sandbox e historial de chat en una página.",
    slideControlsAlt: "Controles de tarea y ruta de modelo en la app web AgInTiFlow.",
    slideControlsTitle: "Controles de ruta y tarea",
    slideControlsText: "Elige enrutamiento inteligente, proveedor/modelo manual, acceso shell, cwd y política de instalación.",
    slideLogsAlt: "Salida de AgInTiFlow con logs de sesión estructurados.",
    slideLogsTitle: "Logs estructurados",
    slideLogsText: "Observa cada respuesta del modelo, llamada de herramienta, resultado de comando y respuesta final durante la ejecución.",
    slideHistoryAlt: "Panel de historial de conversación de AgInTiFlow después de una ejecución mock.",
    slideHistoryTitle: "Reanudar la conversación",
    slideHistoryText: "Las sesiones conservan el historial para que las solicitudes de seguimiento continúen desde la ejecución seleccionada.",
    slideMobileAlt: "Diseño móvil responsive de AgInTiFlow.",
    slideMobileTitle: "Responsive por defecto",
    slideMobileText: "Los mismos controles siguen siendo útiles en pantallas estrechas para supervisión y configuración rápidas.",
    platformEyebrow: "Automatización de proyectos de bajo costo",
    platformTitle: "Un workspace, modelos enrutados y herramientas visibles.",
    featureRoutingTitle: "Enrutamiento inteligente",
    featureRoutingText: "DeepSeek v4 flash maneja trabajo rápido. DeepSeek v4 pro maneja tareas complejas. Las rutas manuales compatibles con OpenAI siguen disponibles.",
    featureWrappersTitle: "Herramientas wrapper",
    featureWrappersText: "Los wrappers de Codex, Claude, Gemini, Copilot y Qwen son herramientas asesoras opcionales, no dependencias obligatorias.",
    featureFilesTitle: "Herramientas de archivo seguras",
    featureFilesText: "Lista, lee, busca, escribe y aplica parches a archivos del workspace con guardrails de ruta, hashes y diffs compactos.",
    featureMockTitle: "Modo mock",
    featureMockText: "El enrutamiento mock local verifica UI, API, herramientas y rutas smoke de CI sin credenciales DeepSeek u OpenAI.",
    safetyEyebrow: "Modelo de seguridad",
    safetyTitle: "Automatización útil con límites explícitos.",
    safetyText: "AgInTiFlow mantiene los comandos locales bajo allowlist, guarda historial reanudable y expone estado de sandbox mediante APIs que no filtran claves API ni tokens npm.",
    safetyItem1: "Modo Docker de solo lectura para inspección y pruebas.",
    safetyItem2: "Modo Docker con escritura en workspace solo para comandos de configuración aprobados.",
    safetyItem3: "Las ediciones permanecen dentro del directorio de comandos elegido y bloquean rutas parecidas a secretos.",
    safetyItem4: "Las instalaciones de paquetes requieren aprobación por defecto.",
    safetyItem5: "Publicación NPM, comandos de tokens, sudo, git destructivo y encadenamiento shell están bloqueados.",
    bottomSummaryAria: "Resumen de AgInTiFlow",
    bottomStatement: "AgInTiFlow enruta el trabajo normal por DeepSeek v4 flash, escala tareas complejas a DeepSeek v4 pro, edita archivos del workspace con herramientas protegidas y puede llamar wrappers de Codex, Claude, Gemini, Copilot y Qwen cuando aportan valor.",
    footerProduct: "AgInTiFlow por AgInTi Inc.",
  },
  fr: {
    documentTitle: "AgInTiFlow | Agents à faible coût conscients du projet",
    metaDescription:
      "AgInTiFlow est un espace de travail agent Web et CLI avec routage DeepSeek/Venice/OpenAI, appels d’outils visibles, sessions durables, scouts, supervision SCS, workflows AAPS et exécution locale protégée.",
    brandHomeAria: "Accueil AgInTiFlow",
    primaryNavAria: "Navigation principale",
    navScreenshots: "Captures",
    navPlatform: "Plateforme",
    navSafety: "Sécurité",
    navLaunch: "Lancer l’interface web",
    languageLabel: "Langue",
    heroEyebrow: "Espace agent Web + CLI",
    heroTitle: "AgInTi Flow -- agents à faible coût conscients du projet",
    heroSubtitle: "Utilisez le même espace de travail agent depuis le Web ou le CLI, avec routage DeepSeek/Venice/OpenAI, appels d’outils visibles, sessions durables, scouts, supervision SCS, workflows AAPS et exécution locale protégée.",
    installAria: "Installer AgInTiFlow",
    copyButton: "Copier",
    copiedPrefix: "Copié : {text}",
    copyFailed: "La copie a échoué. Sélectionnez la commande et copiez-la manuellement.",
    heroScreenshots: "Voir les vraies captures de l’app",
    capabilitySummaryAria: "Résumé des capacités AgInTiFlow",
    cardDefaultLabel: "Route par défaut",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "Planification rapide pour navigateur, shell et petites tâches de code.",
    cardEscalationLabel: "Escalade",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "Implémentation complexe, débogage et décisions de conception.",
    cardSafetyLabel: "Exécution sûre",
    cardSafetyTitle: "Docker + politique",
    cardSafetyText: "Lecture seule par défaut, approbation explicite pour les commandes de configuration.",
    screensEyebrow: "Captures réelles de l’application locale",
    screensTitle: "Le travail quotidien avec un agent doit être inspectable, pas mystérieux.",
    screensText: "Le carrousel utilise des captures de l’application AgInTiFlow active sur http://127.0.0.1:3210/.",
    screensCarouselAria: "Captures AgInTiFlow",
    previousScreenshotAria: "Capture précédente",
    nextScreenshotAria: "Capture suivante",
    screenshotSelectorAria: "Sélecteur de captures",
    showScreenshotAria: "Afficher la capture {number}",
    slideOverviewAlt: "Application web AgInTiFlow montrant les contrôles de tâche, la sortie d’exécution et l’historique.",
    slideOverviewTitle: "Cockpit d’agent",
    slideOverviewText: "Routage, sortie mock, état des wrappers, contrôles sandbox et historique de chat dans une seule page.",
    slideControlsAlt: "Contrôles de tâche et de route modèle dans l’application web AgInTiFlow.",
    slideControlsTitle: "Contrôles de route et de tâche",
    slideControlsText: "Choisissez routage intelligent, fournisseur/modèle manuel, accès shell, cwd de commande et politique d’installation.",
    slideLogsAlt: "Sortie AgInTiFlow avec journaux de session structurés.",
    slideLogsTitle: "Journaux structurés",
    slideLogsText: "Voyez chaque réponse modèle, appel d’outil, résultat de commande et réponse finale pendant l’exécution.",
    slideHistoryAlt: "Panneau d’historique AgInTiFlow après une exécution mock.",
    slideHistoryTitle: "Reprendre la conversation",
    slideHistoryText: "Les sessions conservent l’historique pour que les demandes suivantes continuent depuis l’exécution choisie.",
    slideMobileAlt: "Mise en page mobile responsive d’AgInTiFlow.",
    slideMobileTitle: "Responsive par défaut",
    slideMobileText: "Les mêmes contrôles restent utilisables sur petit écran pour la surveillance et la configuration rapides.",
    platformEyebrow: "Automatisation de projet à faible coût",
    platformTitle: "Un workspace, des modèles routés, des outils visibles.",
    featureRoutingTitle: "Routage intelligent",
    featureRoutingText: "DeepSeek v4 flash traite le travail rapide. DeepSeek v4 pro traite les tâches complexes. Les routes manuelles compatibles OpenAI restent disponibles.",
    featureWrappersTitle: "Outils wrapper",
    featureWrappersText: "Les wrappers Codex, Claude, Gemini, Copilot et Qwen sont des outils consultatifs optionnels, pas des dépendances obligatoires.",
    featureFilesTitle: "Outils de fichiers sûrs",
    featureFilesText: "Lister, lire, chercher, écrire et patcher les fichiers du workspace avec garde-fous de chemin, hashes et diffs compacts.",
    featureMockTitle: "Mode mock",
    featureMockText: "Le routage mock local vérifie UI, API, exécution d’outils et chemins smoke CI sans identifiants DeepSeek ou OpenAI.",
    safetyEyebrow: "Modèle de sécurité",
    safetyTitle: "Automatisation utile avec limites explicites.",
    safetyText: "AgInTiFlow garde les commandes locales sous allowlist, stocke l’historique réutilisable et expose l’état sandbox via des APIs qui ne divulguent ni clés API ni tokens npm.",
    safetyItem1: "Mode Docker lecture seule pour inspection et tests.",
    safetyItem2: "Mode Docker écriture workspace uniquement pour les commandes de configuration approuvées.",
    safetyItem3: "Les éditions restent dans le répertoire de commande choisi et bloquent les chemins ressemblant à des secrets.",
    safetyItem4: "Les installations de paquets demandent une approbation par défaut.",
    safetyItem5: "Publication NPM, commandes de tokens, sudo, git destructeur et chaînage shell sont bloqués.",
    bottomSummaryAria: "Résumé AgInTiFlow",
    bottomStatement: "AgInTiFlow route le travail normal via DeepSeek v4 flash, escalade les tâches complexes vers DeepSeek v4 pro, édite les fichiers du workspace avec des outils protégés et peut appeler Codex, Claude, Gemini, Copilot et Qwen quand ils ajoutent de la valeur.",
    footerProduct: "AgInTiFlow par AgInTi Inc.",
  },
  ja: {
    documentTitle: "AgInTiFlow | 低コストでプロジェクトを理解するエージェント",
    metaDescription:
      "AgInTiFlowは、DeepSeek/Venice/OpenAIルーティング、見えるツール呼び出し、永続セッション、scouts、SCS監督、AAPSワークフロー、保護されたローカル実行を備えたWeb + CLIエージェントワークスペースです。",
    brandHomeAria: "AgInTiFlow ホーム",
    primaryNavAria: "メインナビゲーション",
    navScreenshots: "スクリーンショット",
    navPlatform: "プラットフォーム",
    navSafety: "安全性",
    navLaunch: "Web UIを起動",
    languageLabel: "言語",
    heroEyebrow: "Web + CLI エージェントワークスペース",
    heroTitle: "AgInTi Flow -- 低コストでプロジェクトを理解するエージェント",
    heroSubtitle: "Web または CLI から同じエージェントワークスペースを使い、DeepSeek/Venice/OpenAI ルーティング、見えるツール呼び出し、永続セッション、scouts、SCS 監督、AAPS ワークフロー、保護されたローカル実行を扱えます。",
    installAria: "AgInTiFlowをインストール",
    copyButton: "コピー",
    copiedPrefix: "コピーしました: {text}",
    copyFailed: "コピーに失敗しました。コマンドを選択して手動でコピーしてください。",
    heroScreenshots: "実際のアプリ画面を見る",
    capabilitySummaryAria: "AgInTiFlow 機能概要",
    cardDefaultLabel: "デフォルト経路",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "ブラウザ、シェル、短いコーディングタスクを高速に計画します。",
    cardEscalationLabel: "高度な経路",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "複雑な実装、デバッグ、設計判断を扱います。",
    cardSafetyLabel: "安全な実行",
    cardSafetyTitle: "Docker + ポリシー",
    cardSafetyText: "既定は読み取り専用。セットアップコマンドには明示的な承認が必要です。",
    screensEyebrow: "ローカルアプリからの実画面",
    screensTitle: "日常のエージェント作業は、謎ではなく検査可能であるべきです。",
    screensText: "このカルーセルは http://127.0.0.1:3210/ で動くAgInTiFlowアプリから取得した画面を使っています。",
    screensCarouselAria: "AgInTiFlow スクリーンショット",
    previousScreenshotAria: "前のスクリーンショット",
    nextScreenshotAria: "次のスクリーンショット",
    screenshotSelectorAria: "スクリーンショット選択",
    showScreenshotAria: "スクリーンショット {number} を表示",
    slideOverviewAlt: "タスク操作、実行出力、会話履歴を表示するAgInTiFlow Webアプリ。",
    slideOverviewTitle: "エージェントのコックピット",
    slideOverviewText: "ルート制御、モック出力、ラッパー状態、サンドボックス制御、チャット履歴を1ページに集約。",
    slideControlsAlt: "AgInTiFlow Webアプリのタスクとモデル経路の操作。",
    slideControlsTitle: "経路とタスクの操作",
    slideControlsText: "スマートルーティング、手動プロバイダ/モデル、シェルアクセス、作業ディレクトリ、パッケージ方針を選択します。",
    slideLogsAlt: "構造化されたセッションログを含むAgInTiFlow実行出力。",
    slideLogsTitle: "構造化された実行ログ",
    slideLogsText: "モデル応答、ツール呼び出し、コマンド結果、最終回答を実行中に確認できます。",
    slideHistoryAlt: "モック実行後のAgInTiFlow会話履歴パネル。",
    slideHistoryTitle: "会話を再開",
    slideHistoryText: "セッションはチャット履歴を保存し、選択した実行から続きの依頼を処理できます。",
    slideMobileAlt: "AgInTiFlowのレスポンシブなモバイルレイアウト。",
    slideMobileTitle: "既定でレスポンシブ",
    slideMobileText: "同じ操作が狭い画面でも使いやすく、素早い監視と設定ができます。",
    platformEyebrow: "低コストなプロジェクト自動化",
    platformTitle: "ひとつのワークスペース、ルーティングされたモデル、見えるツール。",
    featureRoutingTitle: "スマートルーティング",
    featureRoutingText: "DeepSeek v4 flashは高速作業を処理し、DeepSeek v4 proは複雑なタスクを処理します。手動のOpenAI互換経路も利用できます。",
    featureWrappersTitle: "ラッパーツール",
    featureWrappersText: "Codex、Claude、Gemini、Copilot、Qwenのラッパーは任意の助言ツールであり、必須依存ではありません。",
    featureFilesTitle: "安全なファイルツール",
    featureFilesText: "ワークスペースファイルを一覧、読取、検索、書込、パッチでき、パスガード、ハッシュ、簡潔なdiffを記録します。",
    featureMockTitle: "モックモード",
    featureMockText: "ローカルモックルーティングで、DeepSeekやOpenAIの資格情報なしにUI、API、ツール実行、CIスモーク経路を検証します。",
    safetyEyebrow: "安全モデル",
    safetyTitle: "明示的な境界を持つ実用的な自動化。",
    safetyText: "AgInTiFlowはローカルコマンドを許可リストで守り、再開可能な実行履歴を保存し、APIキーやnpmトークンを漏らさないAPIでサンドボックス状態を公開します。",
    safetyItem1: "検査とテスト用のDocker読み取り専用モード。",
    safetyItem2: "承認済みセットアップコマンドだけにDockerワークスペース書き込みモードを使用。",
    safetyItem3: "ワークスペース編集は選択したコマンドディレクトリ内に限定し、秘密情報らしいパスをブロックします。",
    safetyItem4: "パッケージインストールは既定で承認が必要です。",
    safetyItem5: "NPM公開、トークンコマンド、sudo、破壊的git、シェル連結はブロックされます。",
    bottomSummaryAria: "AgInTiFlow 概要",
    bottomStatement: "AgInTiFlowは通常作業をDeepSeek v4 flashにルーティングし、複雑なタスクをDeepSeek v4 proにエスカレーションし、保護されたツールでワークスペースファイルを編集し、価値がある場合はCodex、Claude、Gemini、Copilot、Qwenラッパーを呼び出せます。",
    footerProduct: "AgInTi Inc. の AgInTiFlow",
  },
  ko: {
    documentTitle: "AgInTiFlow | 저비용 프로젝트 인식 에이전트",
    metaDescription:
      "AgInTiFlow는 DeepSeek/Venice/OpenAI 라우팅, 보이는 도구 호출, 영구 세션, scouts, SCS 감독, AAPS 워크플로, 보호된 로컬 실행을 갖춘 Web + CLI 에이전트 작업공간입니다.",
    brandHomeAria: "AgInTiFlow 홈",
    primaryNavAria: "기본 내비게이션",
    navScreenshots: "스크린샷",
    navPlatform: "플랫폼",
    navSafety: "안전",
    navLaunch: "Web UI 실행",
    languageLabel: "언어",
    heroEyebrow: "Web + CLI 에이전트 작업공간",
    heroTitle: "AgInTi Flow -- 저비용 프로젝트 인식 에이전트",
    heroSubtitle: "Web 또는 CLI에서 같은 에이전트 작업공간을 사용하며 DeepSeek/Venice/OpenAI 라우팅, 보이는 도구 호출, 영구 세션, scouts, SCS 감독, AAPS 워크플로, 보호된 로컬 실행을 제공합니다.",
    installAria: "AgInTiFlow 설치",
    copyButton: "복사",
    copiedPrefix: "복사됨: {text}",
    copyFailed: "복사에 실패했습니다. 명령을 선택해 직접 복사하세요.",
    heroScreenshots: "실제 앱 스크린샷 보기",
    capabilitySummaryAria: "AgInTiFlow 기능 요약",
    cardDefaultLabel: "기본 경로",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "브라우저, 셸, 짧은 코딩 작업을 빠르게 계획합니다.",
    cardEscalationLabel: "상위 경로",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "복잡한 구현, 디버깅, 설계 결정을 처리합니다.",
    cardSafetyLabel: "안전 실행",
    cardSafetyTitle: "Docker + 정책",
    cardSafetyText: "기본은 읽기 전용이며, 설정 명령은 명시적 승인이 필요합니다.",
    screensEyebrow: "로컬 앱의 실제 스크린샷",
    screensTitle: "일상적인 에이전트 작업은 불가사의하지 않고 확인 가능해야 합니다.",
    screensText: "이 캐러셀은 http://127.0.0.1:3210/ 에서 실행 중인 AgInTiFlow 앱의 스크린샷을 사용합니다.",
    screensCarouselAria: "AgInTiFlow 스크린샷",
    previousScreenshotAria: "이전 스크린샷",
    nextScreenshotAria: "다음 스크린샷",
    screenshotSelectorAria: "스크린샷 선택기",
    showScreenshotAria: "스크린샷 {number} 보기",
    slideOverviewAlt: "작업 제어, 실행 출력, 대화 기록을 보여주는 AgInTiFlow 웹 앱.",
    slideOverviewTitle: "에이전트 조종석",
    slideOverviewText: "라우트 제어, mock 실행 출력, 래퍼 상태, 샌드박스 제어, 채팅 기록을 한 페이지에서 봅니다.",
    slideControlsAlt: "AgInTiFlow 웹 앱의 작업 및 모델 라우트 제어.",
    slideControlsTitle: "라우트와 작업 제어",
    slideControlsText: "스마트 라우팅, 수동 공급자/모델, 셸 접근, 명령 cwd, 패키지 설치 정책을 선택합니다.",
    slideLogsAlt: "구조화된 세션 로그가 있는 AgInTiFlow 실행 출력.",
    slideLogsTitle: "구조화된 실행 로그",
    slideLogsText: "실행 중 모델 응답, 도구 호출, 명령 결과, 최종 답변을 모두 확인합니다.",
    slideHistoryAlt: "mock 실행 후 AgInTiFlow 대화 기록 패널.",
    slideHistoryTitle: "대화 이어가기",
    slideHistoryText: "세션은 채팅 기록을 보존하여 선택한 실행에서 후속 요청을 계속합니다.",
    slideMobileAlt: "AgInTiFlow 반응형 모바일 레이아웃.",
    slideMobileTitle: "기본 반응형",
    slideMobileText: "좁은 화면에서도 동일한 제어가 빠른 모니터링과 설정에 유용합니다.",
    platformEyebrow: "저비용 프로젝트 자동화",
    platformTitle: "하나의 작업공간, 라우팅된 모델, 보이는 도구.",
    featureRoutingTitle: "스마트 라우팅",
    featureRoutingText: "DeepSeek v4 flash는 빠른 작업을, DeepSeek v4 pro는 복잡한 작업을 처리합니다. 수동 OpenAI 호환 경로도 계속 사용할 수 있습니다.",
    featureWrappersTitle: "래퍼 도구",
    featureWrappersText: "Codex, Claude, Gemini, Copilot, Qwen 래퍼는 선택형 조언 도구이며 필수 의존성이 아닙니다.",
    featureFilesTitle: "안전한 파일 도구",
    featureFilesText: "경로 가드, 해시, 간결한 diff와 함께 워크스페이스 파일을 나열, 읽기, 검색, 쓰기, 패치합니다.",
    featureMockTitle: "Mock 모드",
    featureMockText: "로컬 mock 라우팅으로 DeepSeek나 OpenAI 자격 증명 없이 UI, API, 도구 실행, CI 스모크 경로를 검증합니다.",
    safetyEyebrow: "안전 모델",
    safetyTitle: "명시적 경계가 있는 유용한 자동화.",
    safetyText: "AgInTiFlow는 로컬 명령을 허용 목록으로 보호하고, 재개 가능한 실행 기록을 저장하며, API 키나 npm 토큰을 누출하지 않는 API로 샌드박스 상태를 제공합니다.",
    safetyItem1: "검사와 테스트를 위한 Docker 읽기 전용 모드.",
    safetyItem2: "승인된 설정 명령에만 Docker 워크스페이스 쓰기 모드 사용.",
    safetyItem3: "워크스페이스 편집은 선택한 명령 디렉터리 안에 머물며 비밀처럼 보이는 경로를 차단합니다.",
    safetyItem4: "패키지 설치는 기본적으로 승인이 필요합니다.",
    safetyItem5: "NPM 게시, 토큰 명령, sudo, 파괴적 git, 셸 체이닝은 차단됩니다.",
    bottomSummaryAria: "AgInTiFlow 요약",
    bottomStatement: "AgInTiFlow는 일반 작업을 DeepSeek v4 flash로 라우팅하고, 복잡한 작업을 DeepSeek v4 pro로 상향하며, 보호된 도구로 워크스페이스 파일을 편집하고, 가치가 있을 때 Codex, Claude, Gemini, Copilot, Qwen 래퍼를 호출할 수 있습니다.",
    footerProduct: "AgInTi Inc.의 AgInTiFlow",
  },
  ru: {
    documentTitle: "AgInTiFlow | Недорогие проектно-ориентированные агенты",
    metaDescription:
      "AgInTiFlow — агентное рабочее пространство Web и CLI с маршрутизацией DeepSeek/Venice/OpenAI, видимыми вызовами инструментов, долговечными сессиями, scouts, SCS-супервизией, AAPS-workflows и защищенным локальным выполнением.",
    brandHomeAria: "Главная AgInTiFlow",
    primaryNavAria: "Основная навигация",
    navScreenshots: "Скриншоты",
    navPlatform: "Платформа",
    navSafety: "Безопасность",
    navLaunch: "Запустить Web UI",
    languageLabel: "Язык",
    heroEyebrow: "Web + CLI агентное рабочее пространство",
    heroTitle: "AgInTi Flow -- недорогие проектно-ориентированные агенты",
    heroSubtitle: "Используйте одно и то же агентное рабочее пространство из Web или CLI: маршрутизация DeepSeek/Venice/OpenAI, видимые вызовы инструментов, долговечные сессии, scouts, SCS-супервизия, AAPS-workflows и защищенное локальное выполнение.",
    installAria: "Установить AgInTiFlow",
    copyButton: "Копировать",
    copiedPrefix: "Скопировано: {text}",
    copyFailed: "Не удалось скопировать. Выделите команду и скопируйте вручную.",
    heroScreenshots: "Посмотреть реальные скриншоты приложения",
    capabilitySummaryAria: "Сводка возможностей AgInTiFlow",
    cardDefaultLabel: "Маршрут по умолчанию",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "Быстрое планирование для браузера, shell и коротких задач кодинга.",
    cardEscalationLabel: "Эскалация",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "Сложная реализация, отладка и проектные решения.",
    cardSafetyLabel: "Безопасное выполнение",
    cardSafetyTitle: "Docker + политика",
    cardSafetyText: "По умолчанию только чтение, явное одобрение для setup-команд.",
    screensEyebrow: "Реальные скриншоты из локального приложения",
    screensTitle: "Ежедневная работа агента должна быть проверяемой, а не загадочной.",
    screensText: "Карусель использует скриншоты живого приложения AgInTiFlow на http://127.0.0.1:3210/.",
    screensCarouselAria: "Скриншоты AgInTiFlow",
    previousScreenshotAria: "Предыдущий скриншот",
    nextScreenshotAria: "Следующий скриншот",
    screenshotSelectorAria: "Выбор скриншота",
    showScreenshotAria: "Показать скриншот {number}",
    slideOverviewAlt: "Web-приложение AgInTiFlow с управлением задачами, выводом запуска и историей разговора.",
    slideOverviewTitle: "Кабина агента",
    slideOverviewText: "Управление маршрутами, mock-вывод, статус wrapper, sandbox и история чата на одной странице.",
    slideControlsAlt: "Управление задачей и маршрутом модели в web-приложении AgInTiFlow.",
    slideControlsTitle: "Управление маршрутом и задачей",
    slideControlsText: "Выбирайте smart routing, ручного provider/model, shell-доступ, command cwd и политику установки пакетов.",
    slideLogsAlt: "Вывод AgInTiFlow со структурированными логами сессии.",
    slideLogsTitle: "Структурированные логи",
    slideLogsText: "Видите каждый ответ модели, вызов инструмента, результат команды и финальный ответ во время выполнения.",
    slideHistoryAlt: "Панель истории разговоров AgInTiFlow после mock-запуска.",
    slideHistoryTitle: "Продолжить разговор",
    slideHistoryText: "Сессии сохраняют историю чата, чтобы последующие запросы продолжались из выбранного запуска.",
    slideMobileAlt: "Адаптивный мобильный макет AgInTiFlow.",
    slideMobileTitle: "Адаптивность по умолчанию",
    slideMobileText: "Те же элементы управления остаются удобными на узких экранах для быстрого мониторинга и настройки.",
    platformEyebrow: "Недорогая автоматизация проектов",
    platformTitle: "Один workspace, маршрутизируемые модели, видимые инструменты.",
    featureRoutingTitle: "Smart routing",
    featureRoutingText: "DeepSeek v4 flash выполняет быстрые задачи. DeepSeek v4 pro берет сложные. Ручные OpenAI-compatible маршруты остаются доступны.",
    featureWrappersTitle: "Wrapper-инструменты",
    featureWrappersText: "Wrapper для Codex, Claude, Gemini, Copilot и Qwen — опциональные советники, а не жесткие зависимости.",
    featureFilesTitle: "Безопасные файловые инструменты",
    featureFilesText: "Список, чтение, поиск, запись и patch файлов workspace с защитой путей, hash и компактными diff.",
    featureMockTitle: "Mock-режим",
    featureMockText: "Локальный mock routing проверяет UI, API, выполнение инструментов и CI smoke-пути без учетных данных DeepSeek или OpenAI.",
    safetyEyebrow: "Модель безопасности",
    safetyTitle: "Полезная автоматизация с явными границами.",
    safetyText: "AgInTiFlow держит локальные команды под allowlist, хранит возобновляемую историю запусков и показывает sandbox-статус через API, которые не раскрывают API keys или npm tokens.",
    safetyItem1: "Docker read-only режим для инспекции и тестов.",
    safetyItem2: "Docker workspace-write режим только для одобренных setup-команд.",
    safetyItem3: "Изменения workspace остаются внутри выбранной директории команд и блокируют похожие на secrets пути.",
    safetyItem4: "Установка пакетов по умолчанию требует одобрения.",
    safetyItem5: "NPM publish, token-команды, sudo, destructive git и shell chaining заблокированы.",
    bottomSummaryAria: "Сводка AgInTiFlow",
    bottomStatement: "AgInTiFlow маршрутизирует обычную работу через DeepSeek v4 flash, эскалирует сложные задачи в DeepSeek v4 pro, редактирует workspace-файлы защищенными инструментами и может вызывать Codex, Claude, Gemini, Copilot и Qwen wrappers, когда они добавляют ценность.",
    footerProduct: "AgInTiFlow от AgInTi Inc.",
  },
  vi: {
    documentTitle: "AgInTiFlow | Agent chi phí thấp hiểu dự án",
    metaDescription:
      "AgInTiFlow là workspace agent Web + CLI với routing DeepSeek/Venice/OpenAI, tool call nhìn thấy được, session bền vững, scouts, giám sát SCS, workflow AAPS và thực thi cục bộ có bảo vệ.",
    brandHomeAria: "Trang chủ AgInTiFlow",
    primaryNavAria: "Điều hướng chính",
    navScreenshots: "Ảnh chụp",
    navPlatform: "Nền tảng",
    navSafety: "An toàn",
    navLaunch: "Mở Web UI",
    languageLabel: "Ngôn ngữ",
    heroEyebrow: "Workspace agent Web + CLI",
    heroTitle: "AgInTi Flow -- agent chi phí thấp hiểu dự án",
    heroSubtitle: "Dùng cùng một workspace agent từ Web hoặc CLI, với routing DeepSeek/Venice/OpenAI, tool call nhìn thấy được, session bền vững, scouts, giám sát SCS, workflow AAPS và thực thi cục bộ có bảo vệ.",
    installAria: "Cài đặt AgInTiFlow",
    copyButton: "Sao chép",
    copiedPrefix: "Đã sao chép: {text}",
    copyFailed: "Sao chép thất bại. Hãy chọn lệnh và sao chép thủ công.",
    heroScreenshots: "Xem ảnh chụp app thật",
    capabilitySummaryAria: "Tóm tắt năng lực AgInTiFlow",
    cardDefaultLabel: "Tuyến mặc định",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "Lập kế hoạch nhanh cho trình duyệt, shell và tác vụ code ngắn.",
    cardEscalationLabel: "Nâng cấp",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "Triển khai phức tạp, debug và quyết định thiết kế.",
    cardSafetyLabel: "Thực thi an toàn",
    cardSafetyTitle: "Docker + chính sách",
    cardSafetyText: "Mặc định chỉ đọc, cần phê duyệt rõ ràng cho lệnh thiết lập.",
    screensEyebrow: "Ảnh chụp thật từ app cục bộ",
    screensTitle: "Công việc agent hằng ngày nên dễ kiểm tra, không bí ẩn.",
    screensText: "Carousel dùng ảnh chụp từ app AgInTiFlow đang chạy tại http://127.0.0.1:3210/.",
    screensCarouselAria: "Ảnh chụp AgInTiFlow",
    previousScreenshotAria: "Ảnh chụp trước",
    nextScreenshotAria: "Ảnh chụp tiếp theo",
    screenshotSelectorAria: "Bộ chọn ảnh chụp",
    showScreenshotAria: "Hiển thị ảnh chụp {number}",
    slideOverviewAlt: "Web app AgInTiFlow hiển thị điều khiển tác vụ, output chạy và lịch sử trò chuyện.",
    slideOverviewTitle: "Buồng lái agent",
    slideOverviewText: "Điều khiển tuyến, output mock, trạng thái wrapper, điều khiển sandbox và lịch sử chat trong một trang.",
    slideControlsAlt: "Điều khiển tác vụ và tuyến model trong web app AgInTiFlow.",
    slideControlsTitle: "Điều khiển tuyến và tác vụ",
    slideControlsText: "Chọn smart routing, provider/model thủ công, quyền shell, command cwd và chính sách cài package.",
    slideLogsAlt: "Output AgInTiFlow với log session có cấu trúc.",
    slideLogsTitle: "Log chạy có cấu trúc",
    slideLogsText: "Xem từng phản hồi model, lời gọi tool, kết quả lệnh và câu trả lời cuối khi session chạy.",
    slideHistoryAlt: "Bảng lịch sử trò chuyện AgInTiFlow sau một mock run.",
    slideHistoryTitle: "Tiếp tục cuộc trò chuyện",
    slideHistoryText: "Session lưu lịch sử chat để yêu cầu tiếp theo tiếp tục từ run đã chọn.",
    slideMobileAlt: "Bố cục mobile responsive của AgInTiFlow.",
    slideMobileTitle: "Responsive mặc định",
    slideMobileText: "Cùng bộ điều khiển vẫn dùng tốt trên màn hình hẹp để theo dõi và thiết lập nhanh.",
    platformEyebrow: "Tự động hóa dự án chi phí thấp",
    platformTitle: "Một workspace, model được định tuyến, tool nhìn thấy được.",
    featureRoutingTitle: "Smart routing",
    featureRoutingText: "DeepSeek v4 flash xử lý việc nhanh. DeepSeek v4 pro xử lý tác vụ phức tạp. Các tuyến thủ công tương thích OpenAI vẫn sẵn có.",
    featureWrappersTitle: "Công cụ wrapper",
    featureWrappersText: "Wrapper Codex, Claude, Gemini, Copilot và Qwen là công cụ tư vấn tùy chọn, không phải phụ thuộc bắt buộc.",
    featureFilesTitle: "Công cụ file an toàn",
    featureFilesText: "Liệt kê, đọc, tìm kiếm, ghi và patch file workspace với guardrail đường dẫn, hash và diff gọn.",
    featureMockTitle: "Mock mode",
    featureMockText: "Mock routing cục bộ kiểm tra UI, API, thực thi tool và CI smoke path mà không cần key DeepSeek hoặc OpenAI.",
    safetyEyebrow: "Mô hình an toàn",
    safetyTitle: "Tự động hóa hữu ích với ranh giới rõ ràng.",
    safetyText: "AgInTiFlow giữ lệnh cục bộ trong allowlist, lưu lịch sử chạy có thể resume và cung cấp trạng thái sandbox qua API không làm lộ API key hoặc npm token.",
    safetyItem1: "Docker read-only mode cho kiểm tra và test.",
    safetyItem2: "Docker workspace-write mode chỉ cho lệnh thiết lập đã được phê duyệt.",
    safetyItem3: "Chỉnh sửa workspace nằm trong thư mục lệnh đã chọn và chặn đường dẫn giống secret.",
    safetyItem4: "Cài package mặc định yêu cầu phê duyệt.",
    safetyItem5: "NPM publish, lệnh token, sudo, git phá hủy và shell chaining bị chặn.",
    bottomSummaryAria: "Tóm tắt AgInTiFlow",
    bottomStatement: "AgInTiFlow định tuyến việc thường qua DeepSeek v4 flash, nâng cấp tác vụ phức tạp sang DeepSeek v4 pro, chỉnh sửa file workspace bằng tool có guardrail và có thể gọi wrapper Codex, Claude, Gemini, Copilot, Qwen khi hữu ích.",
    footerProduct: "AgInTiFlow bởi AgInTi Inc.",
  },
  "zh-Hans": {
    documentTitle: "AgInTiFlow | 低成本、项目感知智能体",
    metaDescription:
      "AgInTiFlow 是一个 Web + CLI 智能体工作区，支持 DeepSeek/Venice/OpenAI 路由、可见工具调用、持久会话、scouts、SCS 监督、AAPS 工作流，以及受保护的本地执行。",
    brandHomeAria: "AgInTiFlow 首页",
    primaryNavAria: "主导航",
    navScreenshots: "截图",
    navPlatform: "平台",
    navSafety: "安全",
    navLaunch: "启动 Web UI",
    languageLabel: "语言",
    heroEyebrow: "Web + CLI 智能体工作区",
    heroTitle: "AgInTi Flow -- 低成本、项目感知智能体",
    heroSubtitle: "从 Web 或 CLI 使用同一个智能体工作区，支持 DeepSeek/Venice/OpenAI 路由、可见工具调用、持久会话、scouts、SCS 监督、AAPS 工作流，以及受保护的本地执行。",
    installAria: "安装 AgInTiFlow",
    copyButton: "复制",
    copiedPrefix: "已复制：{text}",
    copyFailed: "复制失败。请选择命令并手动复制。",
    heroScreenshots: "查看真实应用截图",
    capabilitySummaryAria: "AgInTiFlow 能力概览",
    cardDefaultLabel: "默认路由",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "为浏览器、Shell 和短代码任务提供快速规划。",
    cardEscalationLabel: "升级路由",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "处理复杂实现、调试和设计决策。",
    cardSafetyLabel: "安全执行",
    cardSafetyTitle: "Docker + 策略",
    cardSafetyText: "默认只读，设置命令需要明确批准。",
    screensEyebrow: "来自本地应用的真实截图",
    screensTitle: "日常智能体工作应该可检查，而不是神秘黑箱。",
    screensText: "轮播图使用从 http://127.0.0.1:3210/ 运行的 AgInTiFlow 应用捕获的截图。",
    screensCarouselAria: "AgInTiFlow 截图",
    previousScreenshotAria: "上一张截图",
    nextScreenshotAria: "下一张截图",
    screenshotSelectorAria: "截图选择器",
    showScreenshotAria: "显示截图 {number}",
    slideOverviewAlt: "AgInTiFlow Web 应用，显示任务控制、运行输出和对话历史。",
    slideOverviewTitle: "智能体驾驶舱",
    slideOverviewText: "路由控制、Mock 运行输出、包装器状态、沙盒控制和聊天历史集中在一个页面。",
    slideControlsAlt: "AgInTiFlow Web 应用中的任务和模型路由控制。",
    slideControlsTitle: "路由和任务控制",
    slideControlsText: "选择智能路由、手动提供商/模型、Shell 访问、命令工作目录和包安装策略。",
    slideLogsAlt: "带结构化会话日志的 AgInTiFlow 运行输出。",
    slideLogsTitle: "结构化运行日志",
    slideLogsText: "在会话运行时查看每次模型回复、工具调用、命令结果和最终答案。",
    slideHistoryAlt: "Mock 运行后的 AgInTiFlow 对话历史面板。",
    slideHistoryTitle: "继续对话",
    slideHistoryText: "会话会保存聊天历史，后续请求可以从选中的运行继续。",
    slideMobileAlt: "AgInTiFlow 响应式移动布局。",
    slideMobileTitle: "默认响应式",
    slideMobileText: "在窄屏上仍可使用相同控制，便于快速监控和设置。",
    platformEyebrow: "低成本项目自动化",
    platformTitle: "一个工作区，路由模型，可见工具。",
    featureRoutingTitle: "智能路由",
    featureRoutingText: "DeepSeek v4 flash 处理快速工作，DeepSeek v4 pro 处理复杂任务，手动 OpenAI 兼容路由仍可使用。",
    featureWrappersTitle: "包装器工具",
    featureWrappersText: "Codex、Claude、Gemini、Copilot 和 Qwen 包装器是可选咨询工具，不是硬依赖。",
    featureFilesTitle: "安全文件工具",
    featureFilesText: "在路径护栏、哈希和紧凑 diff 保护下，列出、读取、搜索、写入和修补工作区文件。",
    featureMockTitle: "Mock 模式",
    featureMockText: "本地 Mock 路由无需 DeepSeek 或 OpenAI 凭据，就能验证 UI、API、工具执行和 CI 冒烟路径。",
    safetyEyebrow: "安全模型",
    safetyTitle: "有明确边界的实用自动化。",
    safetyText: "AgInTiFlow 通过允许列表保护本地命令，保存可恢复运行历史，并通过不会泄露 API key 或 npm token 的 API 暴露沙盒状态。",
    safetyItem1: "Docker 只读模式用于检查和测试。",
    safetyItem2: "Docker 工作区写入模式只用于已批准的设置命令。",
    safetyItem3: "工作区编辑保持在选定命令目录内，并阻止类似密钥的路径。",
    safetyItem4: "包安装默认需要批准。",
    safetyItem5: "NPM 发布、token 命令、sudo、破坏性 git 和 shell 串联会被阻止。",
    bottomSummaryAria: "AgInTiFlow 概览",
    bottomStatement: "AgInTiFlow 将常规工作路由到 DeepSeek v4 flash，将复杂任务升级到 DeepSeek v4 pro，通过受保护工具编辑工作区文件，并在有价值时调用 Codex、Claude、Gemini、Copilot 和 Qwen 包装器。",
    footerProduct: "AgInTi Inc. 出品的 AgInTiFlow",
  },
  "zh-Hant": {
    documentTitle: "AgInTiFlow | 低成本、專案感知智能體",
    metaDescription:
      "AgInTiFlow 是一個 Web + CLI 智能體工作區，支援 DeepSeek/Venice/OpenAI 路由、可見工具呼叫、持久會話、scouts、SCS 監督、AAPS 工作流，以及受保護的本地執行。",
    brandHomeAria: "AgInTiFlow 首頁",
    primaryNavAria: "主導覽",
    navScreenshots: "截圖",
    navPlatform: "平台",
    navSafety: "安全",
    navLaunch: "啟動 Web UI",
    languageLabel: "語言",
    heroEyebrow: "Web + CLI 智能體工作區",
    heroTitle: "AgInTi Flow -- 低成本、專案感知智能體",
    heroSubtitle: "從 Web 或 CLI 使用同一個智能體工作區，支援 DeepSeek/Venice/OpenAI 路由、可見工具呼叫、持久會話、scouts、SCS 監督、AAPS 工作流，以及受保護的本地執行。",
    installAria: "安裝 AgInTiFlow",
    copyButton: "複製",
    copiedPrefix: "已複製：{text}",
    copyFailed: "複製失敗。請選取命令並手動複製。",
    heroScreenshots: "查看真實應用截圖",
    capabilitySummaryAria: "AgInTiFlow 能力概覽",
    cardDefaultLabel: "預設路由",
    cardDefaultTitle: "DeepSeek v4 flash",
    cardDefaultText: "為瀏覽器、Shell 和短程式任務提供快速規劃。",
    cardEscalationLabel: "升級路由",
    cardEscalationTitle: "DeepSeek v4 pro",
    cardEscalationText: "處理複雜實作、除錯與設計決策。",
    cardSafetyLabel: "安全執行",
    cardSafetyTitle: "Docker + 策略",
    cardSafetyText: "預設唯讀，設定命令需要明確核准。",
    screensEyebrow: "來自本機應用的真實截圖",
    screensTitle: "日常代理工作應該可檢查，而不是神秘黑箱。",
    screensText: "輪播使用從 http://127.0.0.1:3210/ 執行的 AgInTiFlow 應用擷取的截圖。",
    screensCarouselAria: "AgInTiFlow 截圖",
    previousScreenshotAria: "上一張截圖",
    nextScreenshotAria: "下一張截圖",
    screenshotSelectorAria: "截圖選擇器",
    showScreenshotAria: "顯示截圖 {number}",
    slideOverviewAlt: "AgInTiFlow Web 應用，顯示任務控制、執行輸出與對話歷史。",
    slideOverviewTitle: "代理駕駛艙",
    slideOverviewText: "路由控制、Mock 執行輸出、包裝器狀態、沙盒控制與聊天歷史集中在一個頁面。",
    slideControlsAlt: "AgInTiFlow Web 應用中的任務與模型路由控制。",
    slideControlsTitle: "路由與任務控制",
    slideControlsText: "選擇智慧路由、手動提供者/模型、Shell 存取、命令工作目錄與套件安裝策略。",
    slideLogsAlt: "帶結構化會話日誌的 AgInTiFlow 執行輸出。",
    slideLogsTitle: "結構化執行日誌",
    slideLogsText: "在會話執行時查看每次模型回覆、工具呼叫、命令結果與最終答案。",
    slideHistoryAlt: "Mock 執行後的 AgInTiFlow 對話歷史面板。",
    slideHistoryTitle: "繼續對話",
    slideHistoryText: "會話會保存聊天歷史，後續請求可以從選定的執行繼續。",
    slideMobileAlt: "AgInTiFlow 響應式行動版版面。",
    slideMobileTitle: "預設響應式",
    slideMobileText: "在窄螢幕上仍可使用相同控制，便於快速監控與設定。",
    platformEyebrow: "低成本專案自動化",
    platformTitle: "一個工作區，路由模型，可見工具。",
    featureRoutingTitle: "智慧路由",
    featureRoutingText: "DeepSeek v4 flash 處理快速工作，DeepSeek v4 pro 處理複雜任務，手動 OpenAI 相容路由仍可使用。",
    featureWrappersTitle: "包裝器工具",
    featureWrappersText: "Codex、Claude、Gemini、Copilot 和 Qwen 包裝器是可選諮詢工具，不是硬依賴。",
    featureFilesTitle: "安全檔案工具",
    featureFilesText: "在路徑護欄、雜湊與緊湊 diff 保護下，列出、讀取、搜尋、寫入與修補工作區檔案。",
    featureMockTitle: "Mock 模式",
    featureMockText: "本機 Mock 路由無需 DeepSeek 或 OpenAI 憑證，就能驗證 UI、API、工具執行與 CI 冒煙路徑。",
    safetyEyebrow: "安全模型",
    safetyTitle: "有明確邊界的實用自動化。",
    safetyText: "AgInTiFlow 透過允許清單保護本機命令，保存可恢復執行歷史，並透過不會洩露 API key 或 npm token 的 API 暴露沙盒狀態。",
    safetyItem1: "Docker 唯讀模式用於檢查與測試。",
    safetyItem2: "Docker 工作區寫入模式只用於已核准的設定命令。",
    safetyItem3: "工作區編輯保持在選定命令目錄內，並阻止類似密鑰的路徑。",
    safetyItem4: "套件安裝預設需要核准。",
    safetyItem5: "NPM 發布、token 命令、sudo、破壞性 git 和 shell 串接會被阻止。",
    bottomSummaryAria: "AgInTiFlow 概覽",
    bottomStatement: "AgInTiFlow 將一般工作路由到 DeepSeek v4 flash，將複雜任務升級到 DeepSeek v4 pro，透過受保護工具編輯工作區檔案，並在有價值時呼叫 Codex、Claude、Gemini、Copilot 與 Qwen 包裝器。",
    footerProduct: "AgInTi Inc. 出品的 AgInTiFlow",
  },
};

const languageSelect = document.querySelector("#language-select");
const copyButtons = [...document.querySelectorAll("[data-copy-target]")];
const feedback = document.querySelector("#copy-feedback");
const slides = [...document.querySelectorAll(".carousel-slide")];
const dots = document.querySelector(".carousel-dots");
const description = document.querySelector('meta[name="description"]');
let activeIndex = 0;
let currentLanguage = "en";

function normalizeLanguage(language) {
  const normalized = String(language || "").replace("_", "-");
  if (translations[normalized]) return normalized;
  if (/^zh-(tw|hk|mo|hant)$/i.test(normalized)) return "zh-Hant";
  if (/^zh/i.test(normalized)) return "zh-Hans";
  const base = normalized.split("-")[0];
  return translations[base] ? base : "en";
}

function t(key, params = {}) {
  const dictionary = translations[currentLanguage] || translations.en;
  const template = dictionary[key] || translations.en[key] || "";
  return Object.entries(params).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template);
}

function applyText(selector, attribute, keyAttribute) {
  document.querySelectorAll(selector).forEach((element) => {
    const key = element.dataset[keyAttribute];
    const value = t(key);
    if (value) element.setAttribute(attribute, value);
  });
}

function applySplitTitles() {
  document.querySelectorAll("[data-i18n-split-title]").forEach((element) => {
    const value = t(element.dataset.i18nSplitTitle);
    const [main, ...rest] = value.split(/\s+--\s+/);
    const mainElement = element.querySelector(".hero-title-main");
    const subElement = element.querySelector(".hero-title-sub");
    if (mainElement) mainElement.textContent = main || "";
    if (subElement) subElement.textContent = rest.join(" -- ") || "";
  });
}

function applyLanguage(language, { persist = true } = {}) {
  currentLanguage = normalizeLanguage(language);
  const isRtl = currentLanguage === "ar";
  document.documentElement.lang = currentLanguage;
  document.documentElement.dir = isRtl ? "rtl" : "ltr";
  document.title = t("documentTitle");
  if (description) description.content = t("metaDescription");

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = t(element.dataset.i18n);
    if (value) element.textContent = value;
  });
  applySplitTitles();
  applyText("[data-i18n-aria]", "aria-label", "i18nAria");
  applyText("[data-i18n-alt]", "alt", "i18nAlt");
  if (languageSelect) languageSelect.value = currentLanguage;
  if (persist) window.localStorage.setItem(languageStorageKey, currentLanguage);
  renderCarousel();
}

function setFeedback(message) {
  if (!feedback) return;
  feedback.textContent = message;
  window.clearTimeout(setFeedback.timer);
  setFeedback.timer = window.setTimeout(() => {
    feedback.textContent = "";
  }, 1800);
}

async function copyText(text) {
  if (navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return;
    } catch {
      // Fall back for restricted local previews and some automated browsers.
    }
  }

  const area = document.createElement("textarea");
  area.value = text;
  area.setAttribute("readonly", "");
  area.style.position = "fixed";
  area.style.opacity = "0";
  document.body.append(area);
  area.select();
  document.execCommand("copy");
  area.remove();
}

for (const button of copyButtons) {
  button.addEventListener("click", async () => {
    const target = document.querySelector(`#${button.dataset.copyTarget}`);
    const text = target?.textContent?.trim();
    if (!text) return;
    try {
      await copyText(text);
      setFeedback(t("copiedPrefix", { text }));
    } catch {
      setFeedback(t("copyFailed"));
    }
  });
}

function renderCarousel() {
  slides.forEach((slide, index) => {
    slide.classList.toggle("active", index === activeIndex);
    slide.classList.toggle("previous-slide", index === (activeIndex - 1 + slides.length) % slides.length);
    slide.classList.toggle("next-slide", index === (activeIndex + 1) % slides.length);
    slide.setAttribute("aria-hidden", index === activeIndex ? "false" : "true");
  });

  if (!dots) return;
  [...dots.children].forEach((dot, index) => {
    dot.setAttribute("aria-current", index === activeIndex ? "true" : "false");
    dot.setAttribute("aria-label", t("showScreenshotAria", { number: index + 1 }));
  });
}

function goToSlide(index) {
  activeIndex = (index + slides.length) % slides.length;
  renderCarousel();
}

if (dots) {
  slides.forEach((slide, index) => {
    const dot = document.createElement("button");
    dot.type = "button";
    dot.addEventListener("click", () => goToSlide(index));
    dots.append(dot);
  });
}

document.querySelector("[data-carousel-prev]")?.addEventListener("click", () => goToSlide(activeIndex - 1));
document.querySelector("[data-carousel-next]")?.addEventListener("click", () => goToSlide(activeIndex + 1));
languageSelect?.addEventListener("change", (event) => applyLanguage(event.target.value));

document.addEventListener("keydown", (event) => {
  if (event.key === "ArrowLeft") goToSlide(activeIndex - 1);
  if (event.key === "ArrowRight") goToSlide(activeIndex + 1);
});

const initialLanguage = window.localStorage.getItem(languageStorageKey) || navigator.language || "en";
applyLanguage(initialLanguage, { persist: false });
